In [1]:
import numpy as np
import torch

### Tensor Broadcasting

In [3]:
# vector + scalar
m1 = torch.FloatTensor([1, 2])
m2 = torch.FloatTensor([3]) # [3] --> [3, 3]
print(m1 + m2)
print(m1.shape)

tensor([4., 5.])
torch.Size([2])


In [4]:
# vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] --> [[3, 3]]
print(m1 + m2)
print(m1.shape)

tensor([[4., 5.]])
torch.Size([1, 2])


In [7]:
# 2 x 1 vector + 1 x 2 vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)
print(m1.shape)

# [[1, 2]] --> [[1, 2]]
#              [[1, 2]]

# [[3]] --> [[3, 3]]
# [[4]]     [[4, 4]]

tensor([[4., 5.],
        [5., 6.]])
torch.Size([1, 2])


In [8]:
m1 = torch.FloatTensor([1, 2])
m2 = torch.FloatTensor([[3],[4]]) 
print(m1 + m2)
print(m1.shape)

tensor([[4., 5.],
        [5., 6.]])
torch.Size([2])


### Multiplication VS Matrix Multiplication: Cautions for Broadcasting

In [9]:
m1 = torch.FloatTensor([[1, 2], [3, 4]]) # 2 x 2 matrix
m2 = torch.FloatTensor([[1], [2]]) # 2 x 1 matrix
print(m1.matmul(m2))
print(m1 * m2) # elementwise
print(m1.mul(m2)) # elementwise

tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean & Sum

In [11]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())
print(t.mean(dim=0)) # column-wise
print(t.mean(dim=1)) # row-wise
print(t.sum())
print(t.sum(dim=0)) # column-wise
print(t.sum(dim=1)) # row-wise

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


### Max and Argmax

In [16]:
t = torch.FloatTensor([[1, 2], [4, 3]])
print(t)
print(t.max())

tensor([[1., 2.],
        [4., 3.]])
tensor(4.)


In [18]:
print(t.max(dim=0))
print(t.max(dim=0)[0]) # Maxs
print(t.max(dim=0)[1]) # Argmaxs
print(t.max(dim=1)[0]) # Maxs
print(t.max(dim=1)[1]) # Argmaxs

torch.return_types.max(
values=tensor([4., 3.]),
indices=tensor([1, 1]))
tensor([4., 3.])
tensor([1, 1])
tensor([2., 4.])
tensor([1, 0])


In [19]:
print(t.argmax()) # [[1, 2], [3, 4]] --> [[0th, 1st], [2nd, 3rd]]
print(t.argmax(dim=0))

tensor(2)
tensor([1, 1])


## other basic Ops

### View
중요함~

In [22]:
nt = np.array([[[0, 1, 2],
                [3, 4, 5]],
              
               [[6, 7, 8],
                [9, 0, 1]]])
t = torch.FloatTensor(nt)
print(t)
print(t.shape)

tensor([[[0., 1., 2.],
         [3., 4., 5.]],

        [[6., 7., 8.],
         [9., 0., 1.]]])
torch.Size([2, 2, 3])


In [21]:
print(t.view([-1, 3]))
print(t.view([-1, 3]).shape)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.],
        [9., 0., 1.]])
torch.Size([4, 3])


In [24]:
print(t.view([1, -1, 3]))
print(t.view([1, -1, 3]).shape)

tensor([[[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.],
         [9., 0., 1.]]])
torch.Size([1, 4, 3])


### Squeeze & Unsqueeze

In [25]:
t = torch.FloatTensor([[1], [2], [3]])
print(t)
print(t.shape)
print(t.squeeze())
print(t.squeeze().shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([1., 2., 3.])
torch.Size([3])


In [28]:
t = torch.FloatTensor([1, 2, 3])
print(t.shape)
print(t.unsqueeze(0))
print(t.unsqueeze(0).shape)
print(t.unsqueeze(1)) # dim = 1 에 늘려~
print(t.unsqueeze(1).shape)
print(t.unsqueeze(-1)) # 마지막 dim 뒤에 한칸 늘려~
print(t.unsqueeze(-1).shape)

torch.Size([3])
tensor([[1., 2., 3.]])
torch.Size([1, 3])
tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [29]:
# view
print(t.view(1, -1)) # == unsqueeze(0)
print(t.view(1, -1).shape)

tensor([[1., 2., 3.]])
torch.Size([1, 3])


### Type Casting

In [30]:
t = torch.LongTensor([1, 2, 3, 4])
print(t)
print(t.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [35]:
boolt = (t==3)
print(boolt, boolt.type())
print(boolt.long())
print(boolt.float())
boolt = torch.ByteTensor([1, 0, 0, 1])
print(boolt)
print(boolt.long())
print(boolt.float())

tensor([False, False,  True, False]) torch.BoolTensor
tensor([0, 0, 1, 0])
tensor([0., 0., 1., 0.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate & Stacking

In [36]:
x = torch.FloatTensor([[1, 2], [4, 3]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [38]:
print(torch.cat([x, y]))
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [4., 3.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2.],
        [4., 3.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [4., 3., 7., 8.]])


In [39]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [40]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [41]:
print(torch.cat([x,  y, z], dim=1))

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [47]:
print(torch.cat([x.view([1,-1]),  y.view([1,-1]), z.view([1,-1])], dim=0)) # view(1, -1) or unsqueeze(0)
print(torch.cat([x.view([-1,1]),  y.view([-1,1]), z.view([-1,1])], dim=1)) # view(-1, 1) or unsqueeze(1)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Ones and Zeros

In [48]:
x = torch.FloatTensor([[0, 1, 2], [1, 2, 0]])
print(x)
# 같은 device에 선언하는 것!  ex) cpu <--> gpu 등 에러가 날 수 있음! (나중에 쓰일 수 있음)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [1., 2., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operations

In [50]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.)) # x = x.mul(2.)
print(x) # 

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
